version: "3.3"  # optional since v1.27.0
services:

  postgres:
    container_name: db
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: sdcdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./SDCData:/tmp/SDCData
    ports:
      # localport:containerport
      - '5432:5432'

  web:
    container_name: "dockertest"
    build: ./server
    ports:
      - "4444:4444"
    depends_on:
      - "postgres"