version: "3.9"  # optional since v1.27.0
services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      # localport:containerport
      - '5432:5432'

  web:
    container_name: "dockertest"
    build: ./server
    ports:
      - "4444:4444"
    depends_on:
      - "postgres"